package Exception_handling;

public class Exception_Handling_Methods {

	public static void main(String args[]) 
	{
		method1();
		arithmetic_exce();
		array_ind_outof_bound_exce();
		method2();
	}

//if you don't handle the exception, the statements fall after your exception will not be executed

	public static void method1()
	{
		try {
				System.out.println("Executing Method1...");
			}catch(Exception e) {};
	
	}

	public static void arithmetic_exce() 
	{
		try {
				int i = 100 / 0;
				System.out.println(i);
			}catch(Exception e) 
			{
				System.out.println(e.getMessage());
				e.printStackTrace();
			}
	}

	public static void array_ind_outof_bound_exce() 
	{
		try {
			
		}catch(Exception e) {}

	}

	public static void method2()
	{
		try {
				System.out.println("Executing Method2...");
			}catch(Exception e) {}
	}
}